version: '3.8'

services:
  scraper:
    build:
      context: .
      args:
        ENV: ${ENV:-development}
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - .env.${ENV:-development}
    environment:
      - ENV=${ENV:-development}
