version: '3.8'

services:
  scraper:
    build:
      context: .
      args:
        ENV: ${ENV:-production}
    volumes:
      - scraper_data:/app/data
      - ./config:/app/config
    env_file:
      - .env.${ENV:-production}
    environment:
      - ENV=${ENV:-production}
    restart: unless-stopped

volumes:
  scraper_data:
