name: Deploy Scraper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # 每天執行一次

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env.production
        echo "ENV=production" >> .env.production

    - name: Build and run Docker
      run: |
        docker-compose build
        docker-compose up -d

    - name: Health check
      run: |
        sleep 30  # 等待容器啟動
        docker-compose ps
